name:           bisectapp.com

url:            http://bisectapp.com
domain:         bisectapp.com

# Comment out when deploying
# url:              http://localhost:8180
# domain:           localhost:8180

permalink:   /:categories/:year/:title

markdown:    'redcarpet'

redcarpet:
    extensions: [ 'smart', 'no_intra_emphasis', 'autolink' ]

highlighter: 'pygments'

